apiVersion: v2
name: bluerange-server
description: Install BlueRange Server in your Kubernetes cluster
maintainers:
  - name: niels-hb
    email: niels.heidbrink@external.mway.io
  - name: taschenuhr
    email: 29057942+taschenuhr@users.noreply.github.com

type: application

version: 1.2.0

appVersion: "5.33.1"

dependencies:
  - name: mariadb
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.14.3
    condition: mariadb.enabled
  - name: mongodb
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.12.4
    condition: mongodb.enabled
