apiVersion: v2
name: bluerange-mosquitto
description: Install BlueRange Mosquitto in your Kubernetes cluster
maintainers:
  - name: niels-hb
    email: niels.heidbrink@external.mway.io
  - name: taschenuhr
    email: 29057942+taschenuhr@users.noreply.github.com

type: application

version: 1.0.4

appVersion: "25"
