ingress:
  enabled: true
  hosts:
    - host: '{{ required "bluerangeServer.config.relution.server.externalURL is required!" .Values.bluerangeServer.config.relution.server.externalURL | replace "https://" "" }}'
      paths:
        - path: /
          pathType: ImplementationSpecific

autoscaling:
  enabled: true

bluerangeServer:
  config:
    relution:
      server:
        externalURL: https://test.bluerange.io
      database:
        type: mariadb
        url: jdbc:mariadb://mariadb:3306/bluerange
        username: bluerange
        password: bluerange
      mongodb:
        enabled: true
        host: mongodb
        port: 27017
        database: bluerange
        username: bluerange
        password: bluerange

s2s:
  enabled: true
  livenessProbe:
    enabled: false
  psk: "sharedsecret"
  separateChildSas: false
  remote:
    ip: 1.2.3.4
    subnets:
      - 192.168.178.10/32
      - 192.168.178.20/32
      - 192.168.178.30/32
  local:
    nat: 10.10.10.10
    transferSubnet: 10.10.10.10/32

mariadb:
  enabled: true
  fullnameOverride: mariadb

mongodb:
  enabled: true
  fullnameOverride: mongodb

heapDumpExporter:
  enabled: true
  s3:
    bucket: s3://test-bluerange-io
    awsAccessKeyId: bluerange
    awsSecretAccessKey: bluerange
