{{- if .Values.bluerangeMosquitto.config }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "bluerangeMosquitto.fullname" . }}-config
  labels:
    {{- include "bluerangeMosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    {{- .Values.bluerangeMosquitto.config | nindent 4 }}
  {{- if and .Values.bluerangeMosquitto.mqtts.enabled .Values.bluerangeMosquitto.mqtts.config }}
    {{- .Values.bluerangeMosquitto.mqtts.config | nindent 4 }}
  {{- end }}
{{- end }}
