apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bluerangeMosquitto.fullname" . }}
  labels:
    {{- include "bluerangeMosquitto.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bluerangeMosquitto.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.bluerangeMosquitto.config }}
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.bluerangeMosquitto.environment }}
        checksum/environment: {{ include (print $.Template.BasePath "/environment.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.bluerangeMosquitto.secrets }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- end }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bluerangeMosquitto.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bluerangeMosquitto.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.bluerangeMosquitto.config .Values.additionalVolumeMounts }}
          volumeMounts:
          {{- if .Values.bluerangeMosquitto.config }}
            - name: config
              mountPath: /etc/mosquitto/mosquitto.conf
              subPath: mosquitto.conf
          {{- end }}
          {{- if .Values.additionalVolumeMounts }}
            {{- toYaml .Values.additionalVolumeMounts | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if or .Values.bluerangeMosquitto.environment .Values.bluerangeMosquitto.secrets }}
          envFrom:
            {{- if .Values.bluerangeMosquitto.environment }}
            - configMapRef:
                name: {{ include "bluerangeMosquitto.fullname" . }}-environment
            {{- end }}
            {{- if .Values.bluerangeMosquitto.secrets }}
            - secretRef:
                name: {{ include "bluerangeMosquitto.fullname" . }}-secrets
            {{- end }}
          {{- end }}
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: ws
              containerPort: 8001
              protocol: TCP
            {{- if .Values.bluerangeMosquitto.mqtts.enabled }}
            - name: mqtts
              containerPort: 8883
              protocol: TCP
            {{- end }}
            - name: metrics
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.bluerangeMosquitto.config .Values.additionalVolumes }}
      volumes:
      {{- if .Values.bluerangeMosquitto.config }}
        - name: config
          configMap:
            name: {{ include "bluerangeMosquitto.fullname" . }}-config
      {{- end }}
      {{- if .Values.additionalVolumes }}
        {{- toYaml .Values.additionalVolumes | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
