{{- if .Values.bluerangeMosquitto.environment }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "bluerangeMosquitto.fullname" . }}-environment
  labels:
    {{- include "bluerangeMosquitto.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.bluerangeMosquitto.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
