{{- if .Values.ingressRoute.mqtts.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ template "bluerangeMosquitto.fullname" . }}-mqtts
  annotations:
    {{- with .Values.ingressRoute.mqtts.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "bluerangeMosquitto.labels" . | nindent 4 }}
    {{- with .Values.ingressRoute.mqtts.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
  {{- range .Values.ingressRoute.mqtts.entryPoints }}
    - {{ . }}
  {{- end }}
  routes:
    - match: {{ .Values.ingressRoute.mqtts.matchRule }}
      services:
        - name: {{ template "bluerangeMosquitto.fullname" . }}
          port: mqtt
        {{- with .Values.ingressRoute.mqtts.middlewares }}
      middlewares:
        {{- toYaml . | nindent 8 }}
      {{- end -}}
  {{- with .Values.ingressRoute.mqtts.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
