apiVersion: v1
kind: Service
metadata:
  name: {{ include "bluerangeMosquitto.fullname" . }}
  labels:
    {{- include "bluerangeMosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
    - port: 8001
      targetPort: ws
      protocol: TCP
      name: ws
    {{- if .Values.bluerangeMosquitto.mqtts.enabled }}
    - port: 8883
      targetPort: mqtts
      protocol: TCP
      name: mqtts
    {{- end }}
    - port: 3000
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "bluerangeMosquitto.selectorLabels" . | nindent 4 }}
