apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bluerangeServer.fullname" . }}
  labels:
    {{- include "bluerangeServer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bluerangeServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.bluerangeServer.config }}
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.bluerangeServer.environment }}
        checksum/environment: {{ include (print $.Template.BasePath "/environment.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.bluerangeServer.preRunScript }}
        checksum/prerun: {{ include (print $.Template.BasePath "/prerun.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.bluerangeServer.secrets }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- end }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "8099"
        prometheus.io/path: "/actuator/prometheus"
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bluerangeServer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bluerangeServer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or (or .Values.bluerangeServer.config .Values.heapDumpExporter.enabled) .Values.additionalVolumeMounts }}
          volumeMounts:
          {{- if .Values.bluerangeServer.config }}
            - name: config
              mountPath: /opt/relution/application.yml
              subPath: application.yml
          {{- end }}
          {{- if .Values.bluerangeServer.preRunScript }}
            - name: prerun
              mountPath: /opt/relution/prerun.sh
              subPath: prerun.sh
          {{- end }}
          {{- if .Values.heapDumpExporter.enabled }}
            - name: heap-dumps
              mountPath: {{ .Values.heapDumpExporter.directory }}
          {{- end }}
          {{- if .Values.additionalVolumeMounts }}
            {{- toYaml .Values.additionalVolumeMounts | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if or .Values.bluerangeServer.environment .Values.bluerangeServer.secrets }}
          envFrom:
            {{- if .Values.bluerangeServer.environment }}
            - configMapRef:
                name: {{ include "bluerangeServer.fullname" . }}-environment
            {{- end }}
            {{- if .Values.bluerangeServer.secrets }}
            - secretRef:
                name: {{ include "bluerangeServer.fullname" . }}-secrets
            {{- end }}
          {{- end }}
          {{- if or .Values.bluerangeServer.preRunScript .Values.bluerangeServer.existingSecretRefs }}
          env:
            {{- if .Values.bluerangeServer.preRunScript }}
            - name: RELUTION_PRERUN_SCRIPT
              value: /opt/relution/prerun.sh
            {{- end }}
            {{- if .Values.bluerangeServer.existingSecretRefs }}
            {{- toYaml .Values.bluerangeServer.existingSecretRefs | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: monitoring
              containerPort: 8099
              protocol: TCP
          startupProbe:
            httpGet:
              path: /actuator/health
              port: monitoring
            failureThreshold: {{ .Values.startupProbe.failureThreshold | default 30 }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds | default 1 }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: monitoring
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 1 }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: monitoring
            failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 1 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.heapDumpExporter.enabled }}
        - name: heap-dump-exporter
          image: "{{ .Values.heapDumpExporter.image.repository }}:{{ .Values.heapDumpExporter.image.tag }}"
          imagePullPolicy: {{ .Values.heapDumpExporter.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - |
            amazon-linux-extras install -y epel &&
            yum install -y inotify-tools &&
            echo "Listening for changes in directory '{{ .Values.heapDumpExporter.directory }}'..." &&
            inotifywait -m {{ .Values.heapDumpExporter.directory }} -e close_write | while read path action file; do aws s3 --endpoint-url {{ .Values.heapDumpExporter.s3.endpointUrl }} cp "$path$file" "s3://{{ required "heapDumpExporter.s3.bucket is required!" .Values.heapDumpExporter.s3.bucket }}/{{ .Release.Namespace }}/{{ include "bluerangeServer.fullname" . }}/$file"; done;
          env:
            - name: "AWS_ACCESS_KEY_ID"
              value: {{ required "heapDumpExporter.s3.awsAccessKeyId is required!" .Values.heapDumpExporter.s3.awsAccessKeyId }}
            - name: "AWS_SECRET_ACCESS_KEY"
              value: {{ required "heapDumpExporter.s3.awsSecretAccessKey is required!" .Values.heapDumpExporter.s3.awsSecretAccessKey }}
          volumeMounts:
            - name: heap-dumps
              mountPath: {{ .Values.heapDumpExporter.directory }}
        {{- end }}
      {{- if or (or .Values.bluerangeServer.config .Values.heapDumpExporter.enabled) .Values.additionalVolumes }}
      volumes:
      {{- if .Values.bluerangeServer.config }}
        - name: config
          configMap:
            name: {{ include "bluerangeServer.fullname" . }}-config
      {{- end }}
      {{- if .Values.bluerangeServer.preRunScript }}
        - name: prerun
          configMap:
            name: {{ include "bluerangeServer.fullname" . }}-prerun
            defaultMode: 0555
      {{- end }}
      {{- if .Values.heapDumpExporter.enabled }}
        - name: heap-dumps
          emptyDir: {}
      {{- end }}
      {{- if .Values.additionalVolumes }}
        {{- toYaml .Values.additionalVolumes | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
