{{- if .Values.bluerangeServer.environment }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "bluerangeServer.fullname" . }}-environment
  labels:
    {{- include "bluerangeServer.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.bluerangeServer.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
