{{- if .Values.bluerangeServer.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bluerangeServer.fullname" . }}-secrets
  labels:
    {{- include "bluerangeServer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.bluerangeServer.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{ end -}}
{{- end }}
